### ISSUE TITLE
Uncaught TypeError: Cannot set property 'SignaturePad' of undefined

### ISSUE THREAD

**Issue by americanslon** [Mobsites/Blazor.SignaturePad#1]
`Uncaught TypeError: Cannot set property 'SignaturePad' of undefined`

I followed the 4 steps of the installation (nuget, css, js, include) and I get the above error in start-up, meaning not even on the page where the pad actually is. Did I miss something? 
I am using preview 3 and WASM blazor.

**Comment by allan-mobley-jr** [comment]
Is the script link above or below the script link for the Blazor _framework in index.html? If above, move it below.

**Comment by americanslon** [comment]
It was above, putting it below worked. 
You may want to call that part out specifically in the instructions (unless I missed it) - because in the default template, at least when I started my project couple of previews ago, _framework is NOT inside the head tag. 

Thanks!

**Comment by allan-mobley-jr** [comment]
Thanks for your feedback. 

Currently, there is a warning above the <script> tag in the docs, this relates to the <script> tag only. There should definitely be a <script> framework tag for Blazor in default template.

However, I will bring more attention to this in the next and official release for v1.0.0.

Thanks so much!

**Comment by americanslon** [comment]
No no I meant the __framework tag IS there just not in the HEAD, it's in the body. Your doc says to put the JS include as the last thing in the HEAD so it ends up still being above _framework hence the confusion. 

Thanks for your work!

**Comment by allan-mobley-jr** [comment]
My apologies.

Could you point out exactly where you are seeing this in the docs? This needs to be corrected, but I am having trouble finding what you are seeing.

Thanks!

**Comment by americanslon** [comment]
Jesus I am an idiot. I saw this `just above the closing </body> tag,` and read it as `just above the closing </head> tag,` in my head. I am so sorry :)

**Comment by allan-mobley-jr** [comment]
No need to be sorry! And don't call yourself an idiot for that. I miss stuff all the time. It's the nature of what we do.
