### ISSUE TITLE
Setting SiganturePad from image

### ISSUE THREAD

**Issue by americanslon** [Mobsites/Blazor.SignaturePad#12]
While I have your attention - is there a away to set the `SignaturePad` from the bas64 image it itself created? 
I am trying to use `SiganturePad` in a scenario where a signature can be edited.

**Comment by allan-mobley-jr** [comment]
The underlying JavaScript library does have the ability to load a  base64 string. Basically, it passes it to the HTML canvas element.

However, the previous signature strokes themselves could not be edited in this way. Only added to.

**Comment by allan-mobley-jr** [comment]
I currently do not expose this ability in C# but could. If you feel like this would be a useful feature, then I can certainly work it into the next release.

**Comment by americanslon** [comment]
Yeah that's fine. When i said edit I meant more of "clear, then edit" not actually editing strokes.
I just want to use the same control for displaying and editing the sig,

I think it'd be incredibly useful. 
In my app I have a signature attached to an account. The app itself signs a million things so it makes sense to have a singular signature stored per user that gets autopulled anywhere the signature is needed.  
Obliviously, in such setup, I have to have a way to edit the signature. Currently I have to first show an `<img>` of the current signature then have some `edit` button that then hides the `img` and shows the `SignaturePad`. Usable but, imho, clunky for no reason. It'd be much cleaner if `SiganturePad` can just load the existing `base64` signature. That way one control can be used for both add and edit.

**Comment by allan-mobley-jr** [comment]
Let me see if I can pull it off tonight. I have a father's day gathering to attend here shortly, but will see if I can pull it off tonight. It should not be that difficult.

It's the least I can do for dragging the other issue for so long.

At the very least, it should take more than a couple of days. I'll release a preview of it, and you can vet it.

Do you have anything specific in mind as to how you would like to see this functionality play out? I'm thinking a C# method you call on the signature pad that excepts a base64 string/dataURL string.

**Comment by americanslon** [comment]
Yeah that would work. Or a property on `<SignaturePad>` that just gets ignored if it's null or empty. That way there is one less thing to do in `Init`.

No rush. Enjoy your family :) I was just trying to understand if we are talking couple of days or couple of weeks.

Thank you!

**Comment by allan-mobley-jr** [comment]
Now, I remember why I did not expose this functionality when I first started this project.

# fromDataURL

The underlying javascript library that Blazor.SignaturePad utilizes does have a method for reloading a previously drawn signature that was saved as a data URL. Here's how that library's author depicts it:

```javascript
// Draws signature image from data URL.
// NOTE: This method does not populate internal data structure that represents drawn signature. 
//       Thus, after using #fromDataURL, #toData won't work properly.
signaturePad.fromDataURL("data:image/png;base64,iVBORw0K...");
```

The key here is that the signaturePad's `toData()` method "won't work properly" when the `fromDataURL()` method is employed and that said "method does not populate internal data structure".

Much of the current Blazor.SignaturePad functionality relies on that "internal data structure" and its corresponding methods `toData()` and `fromData()`.

For instance, every time a resize event occurs, the signature is redrawn using this "internal data structure" via the `toData()` method. So too when restoring a signature from state (a.k.a, browser storage) when the `KeepState` attribute is used.

# Options

I am investigating the possibility of using only the `toDataURL()` and `fromDataURL()` methods and no longer supporting or relying on the "internal data structure" or its corresponding methods `toData()` and `fromData()`.

# Trade Offs

The only obvious trade off I see from such an approach is that the undoing of a stroke would no longer be possible.

However, the flip side of this is that the feature you requested would be doable.

In my opinion, I think the feature you requested has more inherit value than the ability to undo a stroke (assuming that such an approach does not break more than just the undo functionality),

I let you know later today where I am in the process.

**Comment by americanslon** [comment]
I think so too, at the end of the day its a signature pad not a drawing pad. Its not likely someone will be undoing one stroke of their signature - they'll just redo the whole signature .

**Comment by allan-mobley-jr** [comment]
Very close to a solution. Still working on getting it to render the same dimensions as it was before being saved.

Currently, I am experiencing it being loaded either smaller on larger devices or much larger on smaller devices than originally.

**Comment by allan-mobley-jr** [comment]
# Preview Release

Hey, @americanslon just pushed a preview to nuget:

```script
dotnet add package Mobsites.Blazor.SignaturePad --version 2.0.0-preview1
```

There are two ways to load a previously saved `dataURL` signature:
* via the `DataURL` attribute in html
* via the `FromDataURL()` method on a reference to a `SignaturePad` C# object

These only work in Blazor WASM for now, and I believe I have figured out the reloading issues mentioned above.

Give it a try and let me know how it goes. It will be in preview until I have time to further test it and add support for use in a Blazor Server app.

**Comment by americanslon** [comment]
Works great! I tried the `DataUrl` method and it works exactly as I expected.

The only thing I can really pick on is that the image on the `SignaturePad` is fairly pixelated right after the save(but not the resulting base64 image). It's a bit weird, let me show the steps.

1. I draw on an empty pad. Crisp.
2. I save. `Item.Siganture` now contains the base64 string. `Item.Signature` is also what `DataUrl` is set to. At this point the image on the pad is fairly pixelated.
3. I refresh the same page. Boom - image no longer pixelated.

Even with some pixelation this is good enough. Great work!

**Comment by allan-mobley-jr** [comment]
This is curious. But I'm glad it's working for you. If you see anything else let me know. I truly appreciate you taking the time to let me know.
