### ISSUE TITLE
Only one Control works when Control is used multiple time with different IDs in the same page

### ISSUE THREAD

**Issue by jmaniac** [Mobsites/Blazor.SignaturePad#7]
I am designing an application which demands two signatures on the same page.

I could see only one control works if I have two controls in the same page.

Agreement.razor
```
@using Mobsites.Blazor

<div class="row">
	<div class="detail-wrapper mt50">
		<div class="detail-wrapper-body">
			<h3>Agreement Applicant Signature </h3>
			<SignaturePad Id="Agreement_Applicant_Signature"
						  BackgroundMode="signaturePadBackgroundMode"
						  @ref="Agreement_Applicant_Signature"
						  OnSignatureChange="OnSignatureChangeAgreement">
				<SignaturePadFooter FooterDirective="Sign above">
					<SignaturePadClear Image="clear.png" />
					<SignaturePadUndo Image="undo.png" />
				</SignaturePadFooter>
			</SignaturePad>
		</div>
	</div>
</div>

<div class="row">
	<div class="detail-wrapper mt50">
		<div class="detail-wrapper-body">
			<h3>Privacy Applicant Signature </h3>
			<SignaturePad Id="Privacy_Applicant_Signature "
						  BackgroundMode="signaturePadBackgroundMode"
						  @ref="Privacy_Applicant_Signature"
						  OnSignatureChange="OnSignatureChangePrivacy">
				<SignaturePadFooter FooterDirective="Sign above">
					<SignaturePadClear Image="clear.png" />
					<SignaturePadUndo Image="undo.png" />
				</SignaturePadFooter>
			</SignaturePad>
		</div>
	</div>
</div>


@code {
    SignaturePad Agreement_Applicant_Signature;
    SignaturePad Privacy_Applicant_Signature;

    SignaturePad.SupportedSaveAsTypes signatureType;
    string dataURLAgreementSign, dataURLPrivacySign;

    private async Task OnSignatureChangeAgreement(ChangeEventArgs eventArgs)
    {
        if (eventArgs?.Value != null)
        {
            signatureType = Enum.Parse<SignaturePad.SupportedSaveAsTypes>(eventArgs.Value as string);
        }

        dataURLAgreementSign = await Agreement_Applicant_Signature.ToDataURL(signatureType);
    }

    private async Task OnSignatureChangePrivacy(ChangeEventArgs eventArgs)
    {
        if (eventArgs?.Value != null)
        {
            signatureType = Enum.Parse<SignaturePad.SupportedSaveAsTypes>(eventArgs.Value as string);
        }

        dataURLPrivacySign = await Privacy_Applicant_Signature.ToDataURL(signatureType);
    }

    private BackgroundModes signaturePadBackgroundMode = BackgroundModes.Light;
}
```
Am I missing to set any properties or something?

**Comment by allan-mobley-jr** [comment]
Thanks for raising this issue. I don't see anything that you are missing. I'll look into this and get back to you.

**Comment by allan-mobley-jr** [comment]
This component consists of two representations in its implementation: one in C# and the other in javascript. The Blazor framework keeps track of and knows how many of a component is on the page, whereas the javascript does not and thus only accounts for one representation.

This is a shortcoming on my part. 

I am working on a fix for this, and hope to have something for you before the weekend is out.

**Comment by allan-mobley-jr** [comment]
@jmaniac 

I pushed a fix for this. Could you try nuget package v1.1.2 and see if everything is working now. 

I tested this new release as only one person can, and have a [demo](https://www.mobsites.com/Blazor.SignaturePad/) running with two pads on one page.

Let me know how it goes and whether we can close this issue.

Thanks!

**Comment by uvalleza** [comment]
Looks like I am a little late to reply to this but I was having this exact same issue. In order to solve this I used a Modal. So I created a Modal -> Signature.razor then from my form I called it with three different events and returned the result to a string. From there I was able to display the string as an image/save to db etc... and in my case have up to three different signatures on my one form. 

https://github.com/Blazored/Modal

**Comment by uvalleza** [comment]
Signature.razor

<BlazoredModal />

<SignaturePad @ref="signaturePad" OnSignatureChange="OnSignatureChange"></SignaturePad>
<br />
<br />
<MatButton Raised="true" OnClick="@(() => signaturePad?.Clear())">Clear</MatButton>
<MatButton Raised="true" OnClick="@(SubmitForm)">Save</MatButton>



@code {

    [CascadingParameter] BlazoredModalInstance BlazoredModal { get; set; }

    bool ShowForm { get; set; } = true;
    private SignaturePad signaturePad;
    string signatureBase64Data { get; set; }
    SignaturePad.SupportedSaveAsTypes signatureType;



    private async Task OnSignatureChange(ChangeEventArgs eventArgs)

    {
        if (eventArgs?.Value != null)
        {
            signatureType = Enum.Parse<SignaturePad.SupportedSaveAsTypes>(eventArgs.Value as string);
        }

        signatureBase64Data = await signaturePad.ToDataURL(signatureType);

    }

    void SubmitForm()
    {
        BlazoredModal.Close(ModalResult.Ok(signatureBase64Data));
    }

    void Cancel()
    {
        BlazoredModal.Cancel();
    }

}

**Comment by allan-mobley-jr** [comment]
Nice, work around!

Hopefully, the latest release makes this no longer necessary.

Thanks so much for trying out Blazor Signature Pad and thanks for your feedback.

**Comment by jmaniac** [comment]
Thanks for the great work @allan-mobley-jr. After the upgrade to v1.1.2 solved the issue and works like charm.

**Comment by allan-mobley-jr** [comment]
Awesome! Thanks for your feedback and thanks for trying out Blazor Signature Pad.
